/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day07tictactoe;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Teacher
 */
public class Day07TicTacToe extends javax.swing.JFrame {

    // Model (data) of the game
    enum Player { None, X, O };
    Player[][] board = new Player[3][3];

    int moveNumber; // move number that is about to happen
    
    /* Alternative, but not as nice as enum 
    final static int PLAYER_NONE = 0;
    final static int PLAYER_X = 1;
    final static int PLAYER_O = 2;
    int[][] board2 = new int[3][3]; */
    
    
    /**
     * Creates new form Day07TicTacToe
     */
    public Day07TicTacToe() {
        initComponents();
        resetGame();
    }

    private void resetGame() {
        bt00.setText("");
        bt01.setText("");
        bt02.setText("");
        bt10.setText("");
        bt11.setText("");
        bt12.setText("");
        bt20.setText("");
        bt21.setText("");
        bt22.setText("");
        lblCurrPlayer.setText("X");
        lblCurrTurn.setText("1");
        for (int row = 0; row < 3; row++) {
            for (int col = 0; col < 3; col++) {
                board[row][col] = Player.None;
            }
        }
        moveNumber = 1;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCurrPlayer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCurrTurn = new javax.swing.JLabel();
        btResetGame = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bt00 = new javax.swing.JButton();
        bt01 = new javax.swing.JButton();
        bt02 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();
        bt11 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt20 = new javax.swing.JButton();
        bt21 = new javax.swing.JButton();
        bt22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Turn of player");

        lblCurrPlayer.setText("x/o");

        jLabel3.setText("Turn number");

        lblCurrTurn.setText("1");

        btResetGame.setText("Reset game");
        btResetGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetGameActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        bt00.setText("jButton1");
        bt00.setActionCommand("0,0");
        bt00.setMaximumSize(new java.awt.Dimension(73, 73));
        bt00.setMinimumSize(new java.awt.Dimension(73, 73));
        bt00.setName("0,0"); // NOI18N
        bt00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        jPanel1.add(bt00);

        bt01.setText("jButton2");
        bt01.setActionCommand("0,1");
        bt01.setName("0,1"); // NOI18N
        bt01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        jPanel1.add(bt01);

        bt02.setText("jButton3");
        bt02.setActionCommand("0,2");
        bt02.setName("0,2"); // NOI18N
        bt02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        jPanel1.add(bt02);

        bt10.setText("jButton4");
        bt10.setActionCommand("1,0");
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        jPanel1.add(bt10);

        bt11.setText("jButton5");
        bt11.setActionCommand("1,1");
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        jPanel1.add(bt11);

        bt12.setText("jButton6");
        bt12.setActionCommand("1,2");
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        jPanel1.add(bt12);

        bt20.setText("jButton7");
        bt20.setActionCommand("2,0");
        bt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        jPanel1.add(bt20);

        bt21.setText("jButton8");
        bt21.setActionCommand("2,1");
        bt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        jPanel1.add(bt21);

        bt22.setText("jButton9");
        bt22.setActionCommand("2,2");
        bt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        jPanel1.add(bt22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCurrPlayer)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurrTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btResetGame)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCurrPlayer)
                    .addComponent(jLabel3)
                    .addComponent(lblCurrTurn)
                    .addComponent(btResetGame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btResetGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetGameActionPerformed
        // TODO ask user for confirmation
        resetGame();
    }//GEN-LAST:event_btResetGameActionPerformed

    private void btClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClicked
        // TODO add your handling code here:
        JButton btn = (JButton)evt.getSource();
        String action = btn.getActionCommand();
        String []data = action.split(",");
        int row = Integer.parseInt(data[0]);
        int col = Integer.parseInt(data[1]);
        //
        System.out.printf("Button clicked: %d,%d\n", row, col);
        if (board[row][col] != Player.None) { // already clicked before, not empty
            return;
        }
        String playerStr = (moveNumber % 2 == 1) ? "X" : "O";
        Player player =  (moveNumber % 2 == 1) ? Player.X : Player.O;
        btn.setText(playerStr);
        board[row][col] = player;
        // end-game conditions: current player has 3 or 9 moves done
        if (isPlayerWinner(player)) { 
            JOptionPane.showMessageDialog(this,
                    String.format("Player %s won in %d moves", player, moveNumber),
                    "Game Over",
                    JOptionPane.INFORMATION_MESSAGE);
            resetGame();
            return;
        }
        if (moveNumber == 9) {
            JOptionPane.showMessageDialog(this,
                    String.format("No winner"),
                    "Game Over",
                    JOptionPane.INFORMATION_MESSAGE);
            resetGame();
            return;
        }
        // update turn number and player
        moveNumber++;
        lblCurrTurn.setText(moveNumber + "");
        String nextPlayerStr = (moveNumber % 2 == 1) ? "X" : "O";
        lblCurrPlayer.setText(nextPlayerStr);
    }//GEN-LAST:event_btClicked

    private boolean isPlayerWinner(Player player) {
        // look at the board:
        // 3 in row
        for (int i = 0; i < 3; i++) {
            if (board[i][0] == player && board[i][1] == player && board[i][2] == player) {
                return true;
            }
        }
        // 3 in col
        for (int i = 0; i < 3; i++) {
            if (board[0][i] == player && board[1][i] == player && board[2][i] == player) {
                return true;
            }
        }
        // cross (two cases)
        if (board[0][0] == player && board[1][1] == player && board[2][2] == player) {
            return true;
        }
        if (board[0][2] == player && board[1][1] == player && board[2][0] == player) {
            return true;
        }
        // no, then the game continues
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day07TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day07TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day07TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day07TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day07TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt00;
    private javax.swing.JButton bt01;
    private javax.swing.JButton bt02;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt20;
    private javax.swing.JButton bt21;
    private javax.swing.JButton bt22;
    private javax.swing.JButton btResetGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCurrPlayer;
    private javax.swing.JLabel lblCurrTurn;
    // End of variables declaration//GEN-END:variables
}
