/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day02icecreamselector;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ipd
 */
public class Day02IceCreamSelector extends javax.swing.JFrame {

    DefaultListModel<String> modelAvailableList = new DefaultListModel<>();
    
    DefaultListModel<String> modelSelectedFlavours = new DefaultListModel<>();

    /**
     * Creates new form Day02IceCreamSelector
     */
    public Day02IceCreamSelector() {
        initComponents();
        try (Scanner fileInput = new Scanner(new File("flavours.txt"))) {
            while (fileInput.hasNextLine()) {
                String line = fileInput.nextLine();
                modelAvailableList.addElement(line);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Unable to read flavours.txt file:\n" + ex.getMessage(),
                    "File error",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAvailable = new javax.swing.JList<>();
        btAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSelected = new javax.swing.JList<>();
        btDelete = new javax.swing.JButton();
        btDeleteAll = new javax.swing.JButton();
        btPlaceOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Available flavours:");

        lstAvailable.setModel(modelAvailableList);
        jScrollPane1.setViewportView(lstAvailable);

        btAdd.setText("Add >>");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Selected flavours:");

        lstSelected.setModel(modelSelectedFlavours);
        lstSelected.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstSelected);

        btDelete.setText("Delete scoop");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btDeleteAll.setText("Clear all");
        btDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteAllActionPerformed(evt);
            }
        });

        btPlaceOrder.setText("Save and place order");
        btPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlaceOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(158, 158, 158)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(btDeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btPlaceOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btDeleteAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btPlaceOrder)
                                .addGap(0, 5, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        List<String> selList = lstAvailable.getSelectedValuesList();
        if (selList.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "At least one item must be select to add",
                    "Input error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (String flav : selList) {
            modelSelectedFlavours.addElement(flav);
        }
        lstAvailable.clearSelection();
    }//GEN-LAST:event_btAddActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        String flavour = lstSelected.getSelectedValue();
        if (flavour == null) {
            JOptionPane.showMessageDialog(this,
                    "Item must be select to delete",
                    "Input error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        modelSelectedFlavours.removeElement(flavour);
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteAllActionPerformed
        //Custom button text
        Object[] options = {"Delete all", "Cancel"};
        int result = JOptionPane.showOptionDialog(this,
                "Are you sure you want to delete all selected flavours",
                "Action confirmation",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);
        if (result == JOptionPane.OK_OPTION) {
            modelSelectedFlavours.clear();
        }
    }//GEN-LAST:event_btDeleteAllActionPerformed

    private void btPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlaceOrderActionPerformed
        /* // SMART but TERRIBLE solution
        Object [] flavArrayObj = modelSelectedFlavours.toArray();
        String[] flavArrayStr = Arrays.copyOf(flavArrayObj, flavArrayObj.length, String[].class);
        ArrayList<String> flavoursList = new ArrayList<>(Arrays.asList(flavArrayStr));
        String flavCommaSep = String.join(",", flavoursList); */
        
        // SIMPLE but EFFETIVE and easy to undertsand
        ArrayList<String> flavList2 = new ArrayList<>();
        for (int i = 0; i < modelSelectedFlavours.size(); i++) {
            String flav = modelSelectedFlavours.get(i);
            flavList2.add(flav);
        }
        String flavCommaSep2 = String.join(",", flavList2);
        //
        try (PrintWriter fileOutput = new PrintWriter(new FileWriter("purchases.txt", true))) {
            fileOutput.println(flavCommaSep2);
            modelSelectedFlavours.clear(); // remove all items from list
            JOptionPane.showMessageDialog(this, "Order saved to file.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error writing to file:\n" + ex.getMessage(),
                    "File error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btPlaceOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day02IceCreamSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day02IceCreamSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day02IceCreamSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day02IceCreamSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day02IceCreamSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btDeleteAll;
    private javax.swing.JButton btPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstAvailable;
    private javax.swing.JList<String> lstSelected;
    // End of variables declaration//GEN-END:variables
}
